name: flutter_dsl
description: "Annotation + extension based responsive layout and design-system-friendly DX toolkit for Flutter. No build_runner required."
version: 1.1.0
homepage: https://github.com/hardy716/flutter_dsl
repository: https://github.com/hardy716/flutter_dsl
issue_tracker: https://github.com/hardy716/flutter_dsl/issues

topics:
  - dsl
  - responsive
  - design-system
  - extension
  - widget

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
